Ecommerce_Django/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from account.forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm
from cart import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path("account/", include("account.urls", namespace="account")),
    path("store/", include("store.urls", namespace="store")),

    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('order_review/', views.order_review, name="order-review"),
    path('product-status/', views.product_status, name="product-status"),
    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),
    path('search/', views.search, name="search"),
    path('remove/<int:pk>/', views.cart_remove, name='remove'),
    path('wishlist/<int:id>/', views.add_to_wishlist, name="wishlist"),
    path('wishlists/', views.wishlist, name="wishlisting"),

    path('store/', views.store, name="store"),
    path('order-confirmation/', views.order_confirmation, name="order-confirmation"),
    path('<slug:category_slug>/<slug:slug>/', views.detail, name="detail"),
    path('<slug:slug>/', views.category_detail, name="category_detail")

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("register/", views.account_register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>)/", views.account_activate, name="activate"),
    # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
    # User dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/edit/", views.edit_details, name="edit_details"),
    path("profile/delete_user/", views.delete_user, name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"),
        name="delete_confirmation",
    ),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
]

grocery_shop/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from account.forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm
from cart import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path("account/", include("account.urls", namespace="account")),
    path("store/", include("store.urls", namespace="store")),

    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('order_review/', views.order_review, name="order-review"),
    path('product-status/', views.product_status, name="product-status"),
    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),
    path('search/', views.search, name="search"),
    path('remove/<int:pk>/', views.cart_remove, name='remove'),
    path('wishlist/<int:id>/', views.add_to_wishlist, name="wishlist"),
    path('wishlists/', views.wishlist, name="wishlisting"),

    path('store/', views.store, name="store"),
    path('order-confirmation/', views.order_confirmation, name="order-confirmation"),
    path('<slug:category_slug>/<slug:slug>/', views.detail, name="detail"),
    path('<slug:slug>/', views.category_detail, name="category_detail")

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import include, path

from . import views

app_name = "store"

urlpatterns = [
]

cart/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CouponApplyForm(forms.Form):
    code = forms.CharField()

cart/views.py
import code

from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
import json

from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from requests import request
from django.shortcuts import redirect, HttpResponseRedirect

from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
import json
import datetime

from .paypal import PayPalClient
from store.views import *
from account.views import *
from .forms import CouponApplyForm
from .models import *
from .utils import cookieCart, cartData, guestOrder


def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    disc_price = Coupon.objects.all()
    coupon_apply_form = CouponApplyForm()
    context = {'items': items, 'order': order, 'cartItems': cartItems, 'coupon_apply_form': coupon_apply_form, 'disc_price': disc_price}
    return render(request, 'cart/cartview.html', context)


def cart_remove(request, pk):
    item_to_delete = OrderItem.objects.filter(pk=pk)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect('cart:cart')


def checkout(request):
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'cart/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', productId)

    customer = request.user.id
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.id
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )

        subject = 'Thank You for Your Order'
        message = 'Welcome to Obaju! we appriciate Your business'
        from_email = settings.EMAIL_HOST_USER
        to_list = [order.email, settings.EMAIL_HOST_USER]
        send_mail(subject,message,from_email,to_list,fail_silently=True)

        html = render_to_string('store/order_confirmation.html', {'order': order})
        send_mail('Order Confirmation', 'Your order has been sent!', 'noreply@suryabalasundaram1207@gmail.com', ['mail@suryabalasundaram1207@gmail.com', order.email], fail_silently=False, html_message=html)

    return JsonResponse('Payment submitted..', safe=False)


def product_status(request):
    data = cartData(request)
    user_id = request.user
    order = data['order']
    address = ShippingAddress.objects.all()
    orders = OrderItem.objects.filter(order__customer__name__contains=user_id)
    context = {
        'order': order,
        'orders': orders,
        'address': address
    }
    return render(request, 'cart/product_status.html', context)


def order_review(request):
    data = cartData(request)
    user_id = request.user
    order = data['order']
    orders = OrderItem.objects.filter(order__customer__name__contains=user_id)
    context = {
        'order': order,
        'orders': orders,
    }
    return render(request, 'cart/order_review.html', context)


def customer_orders(request):
    user_id = request.user
    orders = Order.objects.filter(customer__name__contains=user_id)
    context = {
        'orders': orders,
    }
    return render(request, 'cart/customer_orders.html', context)


def search(request):
    q = request.GET.get('q')
    products = Product.objects.filter(Q(name__icontains=q) | Q(description__icontains=q))
    context = {
        'q': q,
        'products': products
    }
    return render(request, 'cart/search.html', context)


#def product_review(request, pk):
    #    user = Customer.objects.all()
    #product = get_object_or_404(Product, pk=pk)
    #if request.method == 'POST' and request.user.is_authenticated:
    #    rating = request.POST.get('rating', 3)
    #   comment = request.POST.get('comment', '')

    #   review = Review.objects.create(product=product, user=request.user, rating=rating, comment=comment)
    #return render(request, 'cart/rating_reviews.html')


@login_required
def add_to_wishlist(request, id):
    product = get_object_or_404(Product, id=id)
    if product.wished_item.filter(id=request.user.id).exists():
        product.wished_item.remove(request.user)
    else:
        product.wished_item.add(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])
    # detail',slug=slug)


@login_required
def wishlist(request):
    new = Product.objects.filter(wished_item=request.user)
    return render(request, 'cart/wishlist.html', {'new': new})


@require_POST
def coupon_apply(request):
    now = timezone.now()
    form = CouponApplyForm(request.POST)
    if form.is_valid():
        code = form.cleaned_data['code']

        try:
            coupon = Coupon.objects.get(code__iexact=code,
                                        valid_from__lte=now,
                                        valid_to__gte=now,
                                        active=True)
        except Coupon.DoesNotExist:
            request.user = None
    return redirect('cart')

cart/templates/cart/cartview.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
<div id="all">
      <div id="content">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <!-- breadcrumb-->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li aria-current="page" class="breadcrumb-item active">Shopping cart</li>
                </ol>
              </nav>
            </div>
            <div id="basket" class="col-lg-9">
              <div class="box">
                <form>

                  <h1>Shopping cart</h1>
                  <p class="text-muted">You currently have {{ order.get_cart_items }} item(s) in your cart.</p>
                  <div class="table-responsive">

                    <table class="table">

                      <thead>
                        <tr>
                          <th colspan="2">Product</th>
                          <th>Quantity</th>
                          <th>Unit price</th>
                          <th>Discount</th>
                          <th colspan="2">Total</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for item in items %}
                        <tr>
                          <td><a href="#"><img src="{{item.product.imageURL}}" alt="White Blouse Armani"></a></td>
                          <td><a href="#">{{ item.product.name }}</a></td>
                          <td>
                              <p class="quantity">{{item.quantity}}</p>
                            <div class="quantity">
							<img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}" style="width:15px">

							<img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}" style="width:15px">
						    </div>
                          </td>
                          <td>{{ item.product.price }}</td>
                          <td>00.00</td>
                          <td>{{ item.get_total }}</td>
                          <td><a href="{% url 'remove' item.pk %}"><i class="fa fa-trash-o"></i></a></td>
                        </tr>
                      {% endfor %}
                      </tbody>
                      <tfoot>
                        <tr>
                          <th colspan="5">Total</th>
                          <th colspan="2">{{ order.get_cart_total }}</th>
                        </tr>
                      </tfoot>
                    </table>

                  </div>
                  <!-- /.table-responsive-->
                  <div class="box-footer d-flex justify-content-between flex-column flex-lg-row">
                    <div class="left"><a href="{% url 'store' %}" class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i> Continue shopping</a></div>
                    <div class="right">
                      <button class="btn btn-outline-secondary"><i class="fa fa-refresh"></i> Update cart</button>
                        <a href="{% url 'checkout' %}" type="submit" class="btn btn-primary">Proceed to checkout<i class="fa fa-chevron-right"></i></a>
                    </div>
                  </div>
                </form>
              </div>
              <!-- /.box-->
              <div class="row same-height-row">
                <div class="col-lg-3 col-md-6">
                  <div class="box same-height">
                    <h3>You may also like these products</h3>
                  </div>
                </div>
                {% for item in items %}
                <div class="col-md-3 col-sm-6">
                  <div class="product same-height">
                    <div class="flip-container">
                      <div class="flipper">
                        <div class="front"><a href=""><img src="{{ item.product.imageURL }}" alt="" class="img-fluid"></a></div>
                        <div class="back"><a href=""><img src="{{ item.product.imageURL }}" alt="" class="img-fluid"></a></div>
                      </div>
                    </div><a href="" class="invisible"><img src="{{ item.product.imageURL }}" alt="" class="img-fluid"></a>
                    <div class="text">
                      <h3>{{ item.product.name }}</h3>
                      <p class="price">{{ item.product.price }}</p>
                    </div>
                  </div><!-- /.product-->
                </div>
                {% endfor %}

              </div>
            </div>
            <!-- /.col-lg-9-->
            <div class="col-lg-3">
              <div id="order-summary" class="box">
                <div class="box-header">
                  <h3 class="mb-0">Order summary</h3>
                </div>
                <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>
                <div class="table-responsive">
                  <table class="table">
                    <tbody>
                      <tr>
                        <td>Order subtotal</td>
                        <th>{{ order.get_cart_total }}</th>
                      </tr>
                      <tr>
                        <td>Shipping and handling</td>
                        <th>00.00</th>
                      </tr>
                      <tr>
                        <td>Coupon Discount</td>
                        <th>{{ order.code }}</th>

                      </tr>
                      <tr class="total">
                        <td>Total</td>
                        <th>{{ order.get_cart_total }}</th>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              
            </div>
            <!-- /.col-md-3-->
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

cart/templates/cart/checkout.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
<div id="all">
      <div id="Decontent">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <!-- breadcrumb-->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li aria-current="page" class="breadcrumb-item active">Checkout</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-9">
              <div class="box">
                <form id="form">
                  <h1>Checkout</h1>
                  <div class="nav flex-column flex-md-row nav-pills text-center"><a href="{% url 'checkout' %}" class="nav-link flex-sm-fill text-sm-center active"> <i class="fa fa-map-marker"></i>Address</a></div>
                  <div class="content py-3">
                    <div class="row" id="user-info">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="firstname">Firstname</label>
                          <input name="firstname" type="text" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="email">Email</label>
                          <input name="email" type="text" class="form-control">
                        </div>
                      </div>
                    </div>
                    <!-- /.row-->
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="address">Address</label>
                          <input name="company" type="text" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-6 col-lg-3">
                        <div class="form-group">
                          <label for="city">City</label>
                          <input name="city" type="text" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-6 col-lg-3">
                        <div class="form-group">
                          <label for="zip">ZIP</label>
                          <input name="zip" type="text" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-6 col-lg-3">
                        <div class="form-group">
                          <label for="state">State</label>
                          <select id="state" class="form-control"></select>
                        </div>
                      </div>
                      <div class="col-md-6 col-lg-3">
                        <div class="form-group">
                          <label for="country">Country</label>
                          <select id="country" class="form-control"></select>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="phone">Telephone</label>
                          <input name="phone" type="text" class="form-control">
                        </div>
                      </div>
                    </div>
                    <!-- /.row-->
                  </div>
                  <div class="box-footer d-flex justify-content-between"><a href="{% url 'cart' %}" class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i>Back to Basket</a>
                      <button id="form-button" type="submit" class="btn btn-primary">Continue to Delivery Method<i class="fa fa-chevron-right"></i></button>
                  </div>
                </form>

                  <br>
			<div class="box-element" id="payment-info">
				<small>Paypal Options</small>
				<!--<button id="make-payment">Make payment</button>-->
				<div id="paypal-button-container"></div>
			</div>

              </div>
              <!-- /.box-->
            </div>
            <!-- /.col-lg-9-->

            <!-- /.col-lg-3-->
          </div>
        </div>
      </div>
    </div>

<script src="https://www.paypal.com/sdk/js?client-id=AW2ZLXfxKaa7yvJHbCADDdNniKGHMvk6fp_C2_5OnS8eMGWmU5oxftwzdHgldQ8M0FciQNswK70cgWpz&currency=INR"></script>

	<script>
		var total = '{{order.get_cart_total}}'
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

        	style: {
                color:  'blue',
                shape:  'rect',
            },

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value:parseFloat(total).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    submitFormData()
                });
            }

        }).render('#paypal-button-container');
    </script>

	<script type="text/javascript">
		var shipping = '{{order.shipping}}'

		if (shipping == 'False'){
		 	document.getElementById('shipping-info').innerHTML = ''
		}

		if (user != 'AnonymousUser'){
		 	document.getElementById('user-info').innerHTML = ''
		 }

		if (shipping == 'False' && user != 'AnonymousUser'){
			//Hide entire form if user is logged in and shipping is false
				document.getElementById('form-wrapper').classList.add("hidden");
				//Show payment if logged in user wants to buy an item that does not require shipping
			    document.getElementById('payment-info').classList.remove("hidden");
		}

		var form = document.getElementById('form')
		form.addEventListener('submit', function(e){
	    	e.preventDefault()
	    	console.log('Form Submitted...')
	    	document.getElementById('form-button').classList.add("hidden");
	    	document.getElementById('payment-info').classList.remove("hidden");
	    })

		/*
	    document.getElementById('make-payment').addEventListener('click', function(e){
	    	submitFormData()
	    })
	    */

	    function submitFormData(){
	    	console.log('Payment button clicked')

	    	var userFormData = {
				'name':null,
				'email':null,
				'total':total,
			}

			var shippingInfo = {
				'address':null,
				'city':null,
				'state':null,
				'zipcode':null,
			}

			if (shipping != 'False'){
	    		shippingInfo.address = form.address.value
		    	shippingInfo.city = form.city.value
		    	shippingInfo.state = form.state.value
		    	shippingInfo.zipcode = form.zipcode.value
	    	}

	    	if (user == 'AnonymousUser'){
	    		userFormData.name = form.name.value
	    		userFormData.email = form.email.value
	    	}

	    	console.log('Shipping Info:', shippingInfo)
	    	console.log('User Info:', userFormData)

	    	var url = "/process_order/"
	    	fetch(url, {
	    		method:'POST',
	    		headers:{
	    			'Content-Type':'applicaiton/json',
	    			'X-CSRFToken':csrftoken,
	    		},
	    		body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo}),

	    	})
	    	.then((response) => response.json())
	    	.then((data) => {
				console.log('Success:', data);
				alert('Transaction completed');

				cart = {}
				document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"

				window.location.href = "{% url 'checkout' %}"

				})
	    }
	</script>
{% endblock content %}

cart/templates/cart/product_status.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
     <div id="all">
      <div id="content">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <!-- breadcrumb-->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li aria-current="page" class="breadcrumb-item"><a href="#">My orders</a></li>
                  <li aria-current="page" class="breadcrumb-item active">Order #{{ order.transaction_id }}</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-3">
              <!--
              *** CUSTOMER MENU ***
              _________________________________________________________
              -->
              <div class="card sidebar-menu">
                <div class="card-header">
                  <h3 class="h4 card-title">Customer section</h3>
                </div>
                <div class="card-body">
                  <ul class="nav nav-pills flex-column"><a href="{% url 'account:user_orders' %}" class="nav-link active"><i class="fa fa-list"></i> My orders</a><a href="customer-wishlist.html" class="nav-link"><i class="fa fa-heart"></i> My wishlist</a><a href="customer-account.html" class="nav-link"><i class="fa fa-user"></i> My account</a><a href="index.html" class="nav-link"><i class="fa fa-sign-out"></i> Logout</a></ul>
                </div>
              </div>
              <!-- /.col-lg-3-->
              <!-- *** CUSTOMER MENU END ***-->
            </div>
            <div id="customer-order" class="col-lg-9">
              <div class="box">
                <h1>Order #{{ order.transaction_id }}</h1>
                <p class="lead">Order #{{ order.transaction_id }} was placed on <strong><b>{{ order.date_ordered }}</b></strong> and is currently <strong>Being prepared</strong>.</p>
                <p class="text-muted">If you have any questions, please feel free to <a href="contact.html">contact us</a>, our customer service center is working for you 24/7.</p>
                <hr>
                <div class="table-responsive mb-4">
                  <table class="table">
                    <thead>
                      <tr>
                        <th colspan="2">Product</th>
                        <th>Quantity</th>
                        <th>Unit price</th>
                        <th>Discount</th>
                        <th>Total</th>
                      </tr>
                    </thead>

                    <tbody>
                  {% for item in orders %}
                      <tr>
                        <td><a href="#"><img src="{{item.product.imageURL}}" alt="White Blouse Armani"></a></td>
                        <td><a href="#">{{ item.product.name }}</a></td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.product.price }}</td>
                        <td>10.00</td>
                        <td>{{ item.get_total }}</td>
                      </tr>
                  {% endfor %}
                    </tbody>

                    <tfoot>
                      <tr>
                        <th colspan="5" class="text-right">Order subtotal</th>
                        <th>{{ order.get_cart_total }}</th>
                      </tr>
                      <tr>
                        <th colspan="5" class="text-right">Shipping and handling</th>
                        <th>10.00</th>
                      </tr>
                      <tr>
                        <th colspan="5" class="text-right">Tax</th>
                        <th>0.00</th>
                      </tr>
                      <tr>
                        <th colspan="5" class="text-right">Total</th>
                        <th>{{ order.get_cart_total }}</th>
                      </tr>
                    </tfoot>
                  </table>

                </div>
                <!-- /.table-responsive-->
                <div class="row addresses">
                  <div class="col-lg-6">
                    <h2>Invoice address</h2>
                      {% for addres in address %}
                    <p>{{ addres.address }}<br>{{ addres.city }}<br>{{ addres.state }}<br>{{ addres.zipcode }}</p>
                       {% endfor %}
                  </div>
                  <div class="col-lg-6">
                    <h2>Shipping address</h2>
                    {% for addres in address %}
                    <p>{{ addres.address }}<br>{{ addres.city }}<br>{{ addres.state }}<br>{{ addres.zipcode }}</p>
                     {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}