Ecommerce_Django/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from account.forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm
from cart import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path("account/", include("account.urls", namespace="account")),
    path("store/", include("store.urls", namespace="store")),

    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('order_review/', views.order_review, name="order-review"),
    path('product-status/', views.product_status, name="product-status"),
    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),
    path('search/', views.search, name="search"),
    path('remove/<int:pk>/', views.cart_remove, name='remove'),
    path('wishlist/<int:id>/', views.add_to_wishlist, name="wishlist"),
    path('wishlists/', views.wishlist, name="wishlisting"),

    path('store/', views.store, name="store"),
    path('order-confirmation/', views.order_confirmation, name="order-confirmation"),
    path('<slug:category_slug>/<slug:slug>/', views.detail, name="detail"),
    path('<slug:slug>/', views.category_detail, name="category_detail")

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("register/", views.account_register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>)/", views.account_activate, name="activate"),
    # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
    # User dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/edit/", views.edit_details, name="edit_details"),
    path("profile/delete_user/", views.delete_user, name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"),
        name="delete_confirmation",
    ),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
]

grocery_shop/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from account.forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm
from cart import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path("account/", include("account.urls", namespace="account")),
    path("store/", include("store.urls", namespace="store")),

    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('order_review/', views.order_review, name="order-review"),
    path('product-status/', views.product_status, name="product-status"),
    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),
    path('search/', views.search, name="search"),
    path('remove/<int:pk>/', views.cart_remove, name='remove'),
    path('wishlist/<int:id>/', views.add_to_wishlist, name="wishlist"),
    path('wishlists/', views.wishlist, name="wishlisting"),

    path('store/', views.store, name="store"),
    path('order-confirmation/', views.order_confirmation, name="order-confirmation"),
    path('<slug:category_slug>/<slug:slug>/', views.detail, name="detail"),
    path('<slug:slug>/', views.category_detail, name="category_detail")

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import include, path

from . import views

app_name = "store"

urlpatterns = [
]

store/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
from django.conf import settings


class Category(models.Model):
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=255)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Product(models.Model):
    COLORS = (
        ('Red', 'Red'),
        ('Yellow', 'Yellow'),
        ('Green', 'Green'),
        ('Black', 'Black'),
        ('White', 'White'),
        ('Pink', 'Pink'),
        ('Maroon', 'Maroon'),
    )
    category = models.ForeignKey('Category', related_name='products', on_delete=models.CASCADE, default=True)
    parent = models.ForeignKey('self', related_name='variants', on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    image1 = models.ImageField(null=True, blank=True)
    image2 = models.ImageField(null=True, blank=True)
    color = models.CharField(max_length=100, null=True, choices=COLORS)
    description = models.TextField(blank=True, null=True)
    num_available = models.IntegerField(default=1)
    num_visits = models.IntegerField(default=0)
    last_visit = models.DateTimeField(blank=True, null=True)
    wished_item = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='favourite',
                  default=None, blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image1.url
        except:
            url = ''
        return url

store/forms.py
from django import forms

from store import models

store/views.py
import random
from datetime import datetime

from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from requests import request
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import redirect

from cart.models import Order
from cart.utils import cartData
from .filters import OrderFilter
from .models import *
from django.utils import timezone
from django.conf import settings
from django.shortcuts import render
from django.http import JsonResponse
import json
import datetime
from .models import *
from django.db.models import Q


# Create your views here.


def index(request):
    data = cartData(request)
    order = data['order']
    popular_products = Product.objects.all().order_by('-num_visits')[0:5]
    category = Category.objects.all()
    context = {'popular_products': popular_products, 'order': order, 'category': category}
    return render(request, 'store/index.html', context)


def store(request):
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    products = Product.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 1)
    try:
        products_list = paginator.page(page)
    except PageNotAnInteger:
        products_list = paginator.page(1)
    except EmptyPage:
        products_list = paginator.page(paginator.num_pages)

    context = {'products': products, 'products_list': products_list, 'cartItems': cartItems, 'order':order}
    return render(request, 'store/store.html', context)


def detail(request, category_slug, slug):
    product = get_object_or_404(Product, slug=slug)
    product.num_visits = product.num_visits + 1
    product.last_visit = datetime.datetime.now()
    recently_viewed_products = Product.objects.all().order_by('-last_visit')[0:4]
    product.save()
    #product = Product.objects.get(pk=pk)
    related_products = list(product.category.products.filter(parent=None).exclude(id=product.id))

    if len(related_products) >= 3:
        related_products = random.sample(related_products, 3)


    if product.parent:
        return redirect('detail', category_slug=category_slug, slug=product.parent.slug)


    context = {
        'product': product,
        'related_products': related_products,
        'recently_viewed_products': recently_viewed_products,
    }
    return render(request, 'store/Item_detail.html', context)


def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = category.products.filter(parent=None)
    context = {
        'category': category,
        'products': products
    }

    return render(request, 'store/category_detail.html', context)


def order_confirmation(request):
    order = Order.objects.get(pk=1)
    return render(request, 'store/order_confirmation.html', {'order': order})

store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Obaju : e-commerce template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700">
    <!-- owl carousel-->
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css'%}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">



      
      <script type="text/javascript">
		var user = '{{request.user}}'

		function getToken(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getToken('csrftoken')

		function getCookie(name) {
		    // Split cookie string and get all individual name=value pairs in an array
		    var cookieArr = document.cookie.split(";");

		    // Loop through the array elements
		    for(var i = 0; i < cookieArr.length; i++) {
		        var cookiePair = cookieArr[i].split("=");

		        if(name === cookiePair[0].trim()) {
		            // Decode the cookie value and return
		            return decodeURIComponent(cookiePair[1]);
		        }
		    }

		    // Return null if not found
		    return null;
		}
		var cart = JSON.parse(getCookie('cart'))

		if (cart === undefined){
			cart = {}
			console.log('Cart Created!', cart)
			document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
		}
		console.log('', cart)

	</script>

  </head>
<body>
    <!-- navbar-->
    <header class="header mb-5">
      <!--
      *** TOPBAR ***
      _________________________________________________________
      -->
      <div id="top">
        <div class="container">
          <div class="row">
            <div class="col-lg-6 offer mb-3 mb-lg-0"><a href="#" class="btn btn-success btn-sm">Offer of the day</a><a href="#" class="ml-1">Get flat 35% off on orders over $50!</a></div>
            <div class="col-lg-6 text-center text-lg-right">
              <ul class="menu list-inline mb-0">
                <li class="list-inline-item"><a href="{% url 'account:login' %}">Login</a></li>
                <li class="list-inline-item"><a href="{% url 'account:register' %}">Register</a></li>
                <li class="list-inline-item"><a href="{% url 'account:logout' %}">Logout</a></li>
                <li class="list-inline-item"><a href="{% url 'account:wishlist' %}">Your Wishlists</a></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- *** TOP BAR END ***-->

      </div>
      <nav class="navbar navbar-expand-lg">
        <div class="container"><a href="index.html" class="navbar-brand home"><img src="{% static 'images/logo.png' %}" alt="Obaju logo" class="d-none d-md-inline-block"><img src="{% static "images/logo-small.png" %}" alt="Obaju logo" class="d-inline-block d-md-none"><span class="sr-only">Obaju - go to homepage</span></a>
          <div class="navbar-buttons">
            <button type="button" data-toggle="collapse" data-target="#navigation" class="btn btn-outline-secondary navbar-toggler"><span class="sr-only">Toggle navigation</span><i class="fa fa-align-justify"></i></button>
            <button type="button" data-toggle="collapse" data-target="#search" class="btn btn-outline-secondary navbar-toggler"><span class="sr-only">Toggle search</span><i class="fa fa-search"></i></button><a href="basket.html" class="btn btn-outline-secondary navbar-toggler"><i class="fa fa-shopping-cart"></i></a>
             </div>
          <div id="navigation" class="collapse navbar-collapse">

                  <ul class="navbar-nav mr-auto">
                  <li class="nav-item"><a href="" class="nav-link active">Home</a></li>
               {% for category in menu_categories %}
                   {% if not category.children.all %}

                      <li class="nav-item dropdown menu-large"><a href="{% url 'category_detail' category.slug %}" data-toggle="dropdown" data-hover="dropdown" data-delay="200" class="dropdown-toggle nav-link">{{ category.title }}<b class="caret"></b></a>
                   {% else %}
                        <li class="nav-item dropdown menu-large"><a href="{% url 'category_detail' category.slug %}" data-toggle="dropdown" data-hover="dropdown" data-delay="200" class="dropdown-toggle nav-link">{{ category.title }}<b class="caret"></b></a>
                         <ul class="dropdown-menu megamenu">
                         {% for subcategory in category.children.all %}
                          <li class="nav-item"><a href="{% url 'category_detail' subcategory.slug %}" class="nav-link">{{ subcategory.title }}</a></li>
                         {% endfor %}
                             </ul>
                   {% endif %}
               {% endfor %}

                         <ul class="dropdown-menu megamenu">
                         <li>
                         <div class="row">
                         <div class="col-md-6 col-lg-3">
                         {% for category in menu_categories %}
                             {% if not category.children.all %}
                               <h5><a href="">cloth</a></h5>
                                  <ul class="list-unstyled mb-3">
                                      {% for subcategory in category.children.all %}
                                      <li class="nav-item"><a href="{% url 'category_detail' subcategory.slug %}" class="nav-link">{{ subcategory.title }}</a></li>
                                      {% endfor %}
                                  </ul>
                             {% endif %}
                         {% endfor %}

                      </div>
                    </div>
                  </li>
                </ul>
              </li>
                  </ul>
          </div>


            <div class="navbar-buttons d-flex justify-content-end">
              <!-- /.nav-collapse-->
              <div id="search-not-mobile" class="navbar-collapse collapse"></div><a data-toggle="collapse" href="#search" class="btn navbar-btn btn-primary d-none d-lg-inline-block"><span class="sr-only">Toggle search</span><i class="fa fa-search"></i></a>
              <div id="basket-overview" class="navbar-collapse collapse d-none d-lg-block"><a href="{% url 'cart' %}" class="btn btn-primary navbar-btn"><i class="fa fa-shopping-cart"></i><span id="cart-total">{{order.get_cart_items}} items in cart</span></a></div>
            </div>
          </div>
        </div>
      </nav>

      <div id="search" class="collapse">
        <div class="container">
          <form method="get" class="ml-auto" action="{% url 'search' %}">
            <div class="input-group">
              <input type="text" placeholder="Search" name="q" class="form-control">
              <div class="input-group-append">
                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </header>
{% block content %}
    {% endblock content %}


<!--
    *** FOOTER ***
    _________________________________________________________
    -->
    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <h4 class="mb-3">Pages</h4>
            <ul class="list-unstyled">
              <li><a href="text.html">About us</a></li>
              <li><a href="text.html">Terms and conditions</a></li>
              <li><a href="faq.html">FAQ</a></li>
              <li><a href="contact.html">Contact us</a></li>
            </ul>
            <hr>
            <h4 class="mb-3">User section</h4>
            <ul class="list-unstyled">
              <li><a href="#" data-toggle="modal" data-target="#login-modal">Login</a></li>
              <li><a href="register.html">Regiter</a></li>
            </ul>
          </div>
          <!-- /.col-lg-3-->
          <div class="col-lg-3 col-md-6">
            <h4 class="mb-3">Top categories</h4>
            <h5>Men</h5>
            <ul class="list-unstyled">
              <li><a href="{% url 'store' %}">T-shirts</a></li>
              <li><a href="{% url 'store' %}">Shirts</a></li>
              <li><a href="{% url 'store' %}">Accessories</a></li>
            </ul>
            <h5>Ladies</h5>
            <ul class="list-unstyled">
              <li><a href="{% url 'store' %}">T-shirts</a></li>
              <li><a href="{% url 'store' %}">Skirts</a></li>
              <li><a href="{% url 'store' %}">Pants</a></li>
              <li><a href="{% url 'store' %}">Accessories</a></li>
            </ul>
          </div>
          <!-- /.col-lg-3-->
          <div class="col-lg-3 col-md-6">
            <h4 class="mb-3">Where to find us</h4>
            <p><strong>Obaju Ltd.</strong><br>13/25 New Avenue<br>New Heaven<br>45Y 73J<br>England<br><strong>Great Britain</strong></p><a href="contact.html">Go to contact page</a>
            <hr class="d-block d-md-none">
          </div>
          <!-- /.col-lg-3-->
          <div class="col-lg-3 col-md-6">
            <h4 class="mb-3">Get the news</h4>
            <p class="text-muted">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
            <form>
              <div class="input-group">
                <input type="text" class="form-control"><span class="input-group-append">
                  <button type="button" class="btn btn-outline-secondary">Subscribe!</button></span>
              </div>
              <!-- /input-group-->
            </form>
            <hr>
            <h4 class="mb-3">Stay in touch</h4>
            <p class="social"><a href="#" class="facebook external"><i class="fa fa-facebook"></i></a><a href="#" class="twitter external"><i class="fa fa-twitter"></i></a><a href="#" class="instagram external"><i class="fa fa-instagram"></i></a><a href="#" class="gplus external"><i class="fa fa-google-plus"></i></a><a href="#" class="email external"><i class="fa fa-envelope"></i></a></p>
          </div>
          <!-- /.col-lg-3-->
        </div>
        <!-- /.row-->
      </div>
      <!-- /.container-->
    </div>
    <!-- /#footer-->
    <!-- *** FOOTER END ***-->


    <!--
    *** COPYRIGHT ***
    _________________________________________________________
    -->
    <div id="copyright">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-2 mb-lg-0">
            <p class="text-center text-lg-left">©2019 Your name goes here.</p>
          </div>
          <div class="col-lg-6">
            <p class="text-center text-lg-right">Template design by <a href="https://bootstrapious.com/">Bootstrapious</a>
              <!-- If you want to remove this backlink, pls purchase an Attribution-free License @ https://bootstrapious.com/p/obaju-e-commerce-template. Big thanks!-->
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- review -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static "assets/js/vendor/jquery.min.js" %}"><\/script>')</script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>


    <!-- *** COPYRIGHT END ***-->
    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"> </script>
    <script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/cart.js' %}"></script>
  </body>
</html>

store/templates/store/category_detail.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
    <div id="all">
      <div id="content">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <!-- breadcrumb-->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url 'store' %}">Home</a></li>
                    {% if category.parent %}
                        <li aria-current="page" class="breadcrumb-item active"><a href="{% url 'category_detail' category.parent.slug %}">{{ category.parent.title }}</a></li>
                    {% endif %}
                   <li class="breadcrumb-item active"><a href="{% url 'category_detail' category.slug %}">{{ category.title }}</a></li>

                </ol>
              </nav>
            </div>
            <div class="col-lg-3">
              <!--
              *** MENUS AND FILTERS ***
              _________________________________________________________
              -->
              <div class="card sidebar-menu mb-4">
                <div class="card-header">
                  <h3 class="h4 card-title">Categories</h3>
                </div>
                <div class="card-body">
                  <ul class="nav nav-pills flex-column category-menu">
                  {% for category in menu_categories %}
                    <li><a href="{% url 'category_detail' category.slug %}" class="nav-link active">{{ category.title }}<span class="badge badge-secondary">42</span></a>
                      <ul class="list-unstyled">
                         {% for subcategory in category.children.all %}
                        <li><a href="{% url 'category_detail' subcategory.slug %}" class="nav-link">{{ subcategory.title }}</a></li>
                         {% endfor %}
                  {% endfor %}
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>

              <!-- *** MENUS AND FILTERS END ***-->
            </div>
            <div class="col-lg-9">
              <div class="box">
                  <h1>{{ category.title }}</h1>
                <p>In our Ladies department we offer wide selection of the best products we have found and carefully selected worldwide.</p>
              </div>

              <div class="row products">
                  {% for product in products %}
                <div class="col-lg-4 col-md-6">
                  <div class="product">
                    <div class="flip-container">
                      <div class="flipper">
                        <div class="front"><a href="detail.html"><img src="{{product.imageURL}}" alt="" class="img-fluid"></a></div>
                        <div class="back"><a href="detail.html"><img src="{{product.imageURL}}" alt="" class="img-fluid"></a></div>
                      </div>
                    </div><a href="detail.html" class="invisible"><img src="{{product.imageURL}}" alt="" class="img-fluid"></a>
                    <div class="text">
                      <h3><a href="detail.html">{{ product.name }}</a></h3>
                      <p class="price">
                        {{ product.price }}
                      </p>
                      <p class="buttons"><a href="{% url 'detail' category.slug product.slug %}" class="btn btn-outline-secondary">View detail</a><a href="basket.html" class="btn btn-primary"><i class="fa fa-shopping-cart"></i>Add to cart</a></p>
                    </div>

                    <!-- /.text-->
                  </div>
                  <!-- /.product            -->
                </div>
                  {% endfor %}
                <!-- /.products-->
              </div>
              <div class="pages">
                <p class="loadMore"><a href="#" class="btn btn-primary btn-lg"><i class="fa fa-chevron-down"></i> Load more</a></p>
                <nav aria-label="Page navigation example" class="d-flex justify-content-center">
                  <ul class="pagination">
                    <li class="page-item"><a href="#" aria-label="Previous" class="page-link"><span aria-hidden="true">«</span><span class="sr-only">Previous</span></a></li>
                    <li class="page-item active"><a href="#" class="page-link">1</a></li>
                    <li class="page-item"><a href="#" class="page-link">2</a></li>
                    <li class="page-item"><a href="#" class="page-link">3</a></li>
                    <li class="page-item"><a href="#" class="page-link">4</a></li>
                    <li class="page-item"><a href="#" class="page-link">5</a></li>
                    <li class="page-item"><a href="#" aria-label="Next" class="page-link"><span aria-hidden="true">»</span><span class="sr-only">Next</span></a></li>
                  </ul>
                </nav>
              </div>
            </div>
            <!-- /.col-lg-9-->
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

store/templates/store/order_confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Obaju</title>
    <style type="text/css">
        html {
            width: 100%;
            -webkit-text-size-adjust: 100%;
            -webkit-background-size: 100%;
        }

        body {
            width: 100%;
            font-family: Arial;
            font-size: 14px;
            background-color: white;
            color: #333333;
        }

        a {
            color: #f1f1f1;
        }
    </style>
</head>
<body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td>
                    <div style="text-align: center;">
                        <h1>Obaju - Order confirmation</h1>
                    </div>
                </td>
            </tr>

            <tr>
                <td>
                    <p>Nice! Your order is successful and will be sent shortly!</p>
                </td>
            </tr>

            <tr>
                <td>
                    {% for item in order.orderitem_set.all %}
                        <p><strong>{{ item.product.name }}</strong> - Quantity: {{ item.quantity }} - Price: ${{ item.product.price }}</p>
                    {% endfor %}
                </td>
            </tr>
        </table>
    </body>
</html>

store/templates/store/results.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
    Searched For:{{ query }}
    {{ products }}
{% endblock content %}